import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import { NextAuthProvider, auth } from '@/shared/nextauth'
import { StyledComponentsRegistryProvider } from '@/shared/antd'
import {CoreLayout} from "@/app/coreLayout";
import {YandexMapsProvider} from "@/shared/yandex_maps";

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  const session = await auth()
  return (
    <html lang="en">
      <body className={inter.className}>
        <NextAuthProvider session={session}>
          <StyledComponentsRegistryProvider>
            <YandexMapsProvider>
              <CoreLayout>
                {children}
              </CoreLayout>
            </YandexMapsProvider>
          </StyledComponentsRegistryProvider>
        </NextAuthProvider>
      </body>
    </html>
  )
}
